version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movie-helper-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env
    networks:
      - movie-helper-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: movie-helper-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - backend
    networks:
      - movie-helper-network

networks:
  movie-helper-network:
    driver: bridge
